## Importing Packages


In [ ]:
import numpy as np
import pandas as pd

## Why Numpy?

Numpy comes installed by default on Google Colaboratory, and Thinkful's Jupyter notebook system also has it preinstalled. That means that you don't need to use pip to install Numpy for your coursework. You should know, however, that when working with Python in a "from scratch" environment, you would need to install Numpy.

>Note: Pandas is built on top of NumPy and is intended to integrate well within a scientific computing environment with many other 3rd party libraries.

Numpy was designed to make manipulating data easy. The fundamental structure that it uses is the *array*.  A Numpy array is a table of elements, all of the same type. Arrays may be one-dimensional, two-, or even higher-dimensional. 

<center>

python4_intro_01.png

</center>

### Numpy Arrays

Each dimension is called an *axis*. In a one-dimensional array, there is only a single axis; in a two- dimensional array, there are two *axes*; and in a three-dimensional array there are three axes, etc. The axes of the array are indexed by integers. We refer to individual values in the array by the index of the axis.

To work with Numpy first import the library.


In [ ]:
# one dimensinal array (column)
a = np.array([5,3,7,2,9,6,1,4,8])
print(a)

[5 3 7 2 9 6 1 4 8]


In [ ]:
# print array by index
print(a[3])

2


In [ ]:
# two dimension array (columns and rows)
b = np.array([[2,4,6],[3,5,7]])
print(b)


array([[2, 4, 6],
       [3, 5, 7]])

In [ ]:
# print array by index
print(b[1,2])

7


In [ ]:
# using ranges
c = np.arange(20,50,3)
print(c)

[20 23 26 29 32 35 38 41 44 47]


In [ ]:
# ..or ones (can be used when you initialize the weights in TensorFlow(ML) and other statistical tasks.)
# much like the zeros() function
f = np.ones((5,8))
# print(f)

f2 = f.reshape(4,10)
print(f2)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
# We can even reshape our array
g = np.arange(20)
print(g)

g2 = g.reshape(4,5)
print(g2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
my_array = np.arange(25).reshape(5,5)

#print the number of axes in the array
print('There are {} axes in this array'.format(my_array.ndim))
# print('There are ' + str(my_array.ndim) + ' axes in this array')

#print the shape of the array
print('This is a {} array'.format(my_array.shape))

#print the size of the array
print('This array contains {} elements'.format(my_array.size))

#print the data type of the elements
print('This array contains values of type: {}'.format(my_array.dtype))

There are 2 axes in this array
This is a (5, 5) array
This array contains 25 elements
This array contains values of type: int64


## Finding the Final Grades

A class of 30 students completed a coursework assessment worth 40% and a final exam worth 60% of the final grade. The grades for the coursework and the marks for the exam are in two arrays. Find the total for each student by adding corresponding grades from the two arrays.

In [ ]:
np.random.seed(9) # "setting the seed": random but repeatable
cw_marks = np.random.randint(0,41,30)
exam_marks = np.random.randint(0,61,30)

In [ ]:
print("--- The coursework scores are below ---")
print(cw_marks)
print("The Final exam scores are below ---")
print (exam_marks)

totals = cw_marks + exam_marks

print("The final student grades are:")
print(totals)

--- The coursework scores are below ---
[28 22  1 22 40 27 33 29 28  0 24 10 29 12 18 22  1 35 11 37 19 38  9 16
 40 13 33 13 29 22]
The Final exam scores are below ---
[50 40  4 53 35 52 58  0 10 56 16  4 47  5 52 24 19 30 40  4 59  8  0  1
 34 45 27 44 51 13]
The final student grades are:
[78 62  5 75 75 79 91 29 38 56 40 14 76 17 70 46 20 65 51 41 78 46  9 17
 74 58 60 57 80 35]


In [ ]:
#Now we can do aggregations on these grades
print('The highest mark in the course was {}'.format(np.max(totals)))
print('The lowest mark in the course was {}'.format(np.min(totals)))
print('The mean grade in the course was {}'.format(np.mean(totals)))
print('The standard deviation of the grades in the course was {}'.format(np.std(totals)))

The highest mark in the course was 91
The lowest mark in the course was 5
The mean grade in the course was 51.4
The standard deviation of the grades in the course was 24.19035620517675


## Pandas: Series

In [ ]:
# You can use a list to create a series (one dimensional)
data = [1,2,3,4]
test_data = pd.Series(data)
print(test_data)

0    1
1    2
2    3
3    4
dtype: int64


In [ ]:
# Using a dictionary gives us an index using keys (one dimensional)
data_dict = {'one': 1, 'two': 2, 'three': 3, 'four': 4 }
test_dict = pd.Series(data_dict)
print(test_dict)

one      1
two      2
three    3
four     4
dtype: int64


In [ ]:
# To review, a series = a single column (one dimensional)
ages = pd.Series(np.array([20,34,28,26,39,35,34,36,38]))
print(ages)

0    20
1    34
2    28
3    26
4    39
5    35
6    34
7    36
8    38
dtype: int64


The numbers on the left are row index numbers that have been automatically generated. Again, imagine a spreadsheet with just a single column, even that spreadsheet will have row numbers on the left.


In [ ]:
# we can use anything as our row index and values, not just numbers
values = np.array(['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th'])
names_list = ['Bucks','Raptors','Celtics','Pacers','Heat','Sixers','Nets','Magic']

teams = pd.Series(values, index=names_list)
print(teams)

Bucks      1st
Raptors    2nd
Celtics    3rd
Pacers     4th
Heat       5th
Sixers     6th
Nets       7th
Magic      8th
dtype: object


In [ ]:
#A Series can also be made from a dictionary
points = {
    'Liverpool':69,
    'Man City':68,
    'Tottenham':60,
    'Arsenal':56,
    'Man United':55
}

standings = pd.Series(points)

print(standings)

Liverpool     69
Man City      68
Tottenham     60
Arsenal       56
Man United    55
dtype: int64


In [ ]:
print('The highest rated team has {} points'.format(standings.max()))
print('The lowest rates tema has {} points'.format(standings.min()))
print('The average point total is {}'.format(standings.mean()))
print('The standard deviation of points in the league is {}'.format(standings.std()))

The highest rated team has 69 points
The lowest rates tema has 55 points
The average point total is 61.6
The standard deviation of points in the league is 6.58027355054484


In [ ]:
#We can also use .describe() to get all the summary statistics
standings.describe()

count     5.000000
mean     61.600000
std       6.580274
min      55.000000
25%      56.000000
50%      60.000000
75%      68.000000
max      69.000000
dtype: float64

## Pandas: DataFrames

In [ ]:
# importing a csv
df = pd.read_csv('https://tf-assets-prod.s3.amazonaws.com/tf-curric/data-analytics-bootcamp/songs.csv')
df.info()

# Check for missing values below 👇🏼

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2229 entries, 0 to 2228
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Song Clean    2229 non-null   object
 1   ARTIST CLEAN  2229 non-null   object
 2   Release Year  1652 non-null   object
 3   COMBINED      2229 non-null   object
 4   First?        2229 non-null   int64 
 5   Year?         2229 non-null   int64 
 6   PlayCount     2229 non-null   int64 
 7   F*G           2229 non-null   int64 
dtypes: int64(4), object(4)
memory usage: 139.4+ KB


In [ ]:
# taking a peek at our data
df.head(3)

# NaN will give us an object instead of a number, why?

Song Clean ARTIST CLEAN Release Year  ... Year?  PlayCount  F*G
0  Caught Up in You  .38 Special         1982  ...     1         82   82
1      Fantasy Girl  .38 Special          NaN  ...     0          3    0
2   Hold On Loosely  .38 Special         1981  ...     1         85   85

[3 rows x 8 columns]

In [ ]:
#Create a dataframe from a dictionary
league_dict = {
    'club':['Man City','Liverpool','Tottenham','Man U','Arsenal'],
    'MP':[29,29,29,29,29],
    'W':[23,21,20,17,17],
    'D':[2,7,1,7,6],
    'L':[4,1,8,5,6],
    'GF':[76,64,56,38,39],
    'GA':[20,15,30,20,39],
    'GD':[56,49,26,20,22],
    'Pts':[71,70,61,58,57]
}
# DataFrame = columns and rows
league_df = pd.DataFrame(league_dict)
league_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   club    5 non-null      object
 1   MP      5 non-null      int64 
 2   W       5 non-null      int64 
 3   D       5 non-null      int64 
 4   L       5 non-null      int64 
 5   GF      5 non-null      int64 
 6   GA      5 non-null      int64 
 7   GD      5 non-null      int64 
 8   Pts     5 non-null      int64 
dtypes: int64(8), object(1)
memory usage: 488.0+ bytes


In [ ]:
league_df.head(10)

club  MP   W  D  L  GF  GA  GD  Pts
0   Man City  29  23  2  4  76  20  56   71
1  Liverpool  29  21  7  1  64  15  49   70
2  Tottenham  29  20  1  8  56  30  26   61
3      Man U  29  17  7  5  38  20  20   58
4    Arsenal  29  17  6  6  39  39  22   57

## Manipulating DataFrames: Columns and Filtering

In [ ]:
# we can also use pandas for other file types
shots_df = pd.read_json('https://tf-assets-prod.s3.amazonaws.com/tf-curric/data-analytics-bootcamp/shots.json')
shots_df.info()
shots_df.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 432 entries, 0 to 431
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   location         432 non-null    object
 1   month            432 non-null    object
 2   number_of_shots  432 non-null    int64 
 3   program_name     432 non-null    object
 4   visits           432 non-null    int64 
 5   year             432 non-null    int64 
dtypes: int64(3), object(3)
memory usage: 20.4+ KB


location month  number_of_shots    program_name  visits  year
0  Far South   OCT             1118  Shots for Tots     436  2010
1  Far South   NOV             1600  Shots for Tots     879  2010
2  Far South   DEC             1379  Shots for Tots     818  2010
3  Far South   JAN             1184  Shots for Tots     602  2010
4  Far South   FEB              761  Shots for Tots     337  2010
5  Far South   MAR              835  Shots for Tots     336  2010
6  Far South   APR              749  Shots for Tots     275  2010
7  Far South   MAY              764  Shots for Tots     251  2010
8  Far South   JUN              644  Shots for Tots     244  2010
9  Far South   JUL              943  Shots for Tots     352  2010

In [ ]:
# it's easy to add a new column to a df.. Much list adding to a list! 👀
shots_df['X']= 0 
shots_df = shots_df.assign(shots_per_visit = shots_df.number_of_shots / shots_df.visits)
shots_df.head(3)

location month  number_of_shots  ...  year  X  shots_per_visit
0  Far South   OCT             1118  ...  2010  0         2.564220
1  Far South   NOV             1600  ...  2010  0         1.820250
2  Far South   DEC             1379  ...  2010  0         1.685819

[3 rows x 8 columns]

In [ ]:
# ..or to remove an old one
# remove one row
shots_up_df = shots_df.drop(0, axis = 0)
# remove one column
shots_up_df = shots_df.drop('X', axis = 1)

# review inplace = shots_up_df = shots_df.drop(0, axis = 0, inpla) HOVER
# inplace=True overrides the original object, usually a DatFrame
# instead of saving a new dataframe to itself, use inplace=True

shots_up_df.head()

location month  number_of_shots  ... visits  year  shots_per_visit
0  Far South   OCT             1118  ...    436  2010         2.564220
1  Far South   NOV             1600  ...    879  2010         1.820250
2  Far South   DEC             1379  ...    818  2010         1.685819
3  Far South   JAN             1184  ...    602  2010         1.966777
4  Far South   FEB              761  ...    337  2010         2.258160

[5 rows x 7 columns]

In [ ]:
# we can also select rows using index location
new_var = shots_df.iloc[50:60]
new_var

location month  number_of_shots  ...  year  X  shots_per_visit
50  Far South   DEC              629  ...  2011  0         2.191638
51  Far South   JAN              827  ...  2011  0         2.851724
52  Far South   FEB              482  ...  2011  0         2.577540
53  Far South   MAR              775  ...  2011  0         2.958015
54  Far South   APR              547  ...  2011  0         3.180233
55  Far South   MAY              583  ...  2011  0         2.989744
56  Far South   JUN              728  ...  2011  0         2.706320
57  Far South   JUL              899  ...  2011  0         2.872204
58  Far South   AUG             2499  ...  2011  0         2.919393
59  Far South   SEP              790  ...  2011  0         2.651007

[10 rows x 8 columns]

In [ ]:
# or rows and columns
shots_df.iloc[50:60, :3]

location
50  Far South
51  Far South
52  Far South
53  Far South
54  Far South
55  Far South
56  Far South
57  Far South
58  Far South
59  Far South
60  Far South
61  Far South
62  Far South
63  Far South
64  Far South
65  Far South
66  Far South
67  Far South
68  Far South
69  Far South

In [ ]:
over_1000 = shots_df['number_of_shots'] > 1000
over_1000.head(10)


0     True
1     True
2     True
3     True
4    False
5    False
6    False
7    False
8    False
9    False
Name: number_of_shots, dtype: bool

In [ ]:
type(over_1000)

pandas.core.series.Series

In [ ]:
over_1000.values

array([ True,  True,  True,  True, False, False, False, False, False,
       False,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False,  True, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True,  True,  True,  True, False,  True, False, False, False,
        True,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True, False, False, False, False,
       False, False,

In [ ]:
# Store only True values using index location (super useful for capstone)
shots_df.iloc[over_1000.values]

location month  number_of_shots  ...  year  X  shots_per_visit
0    Far South   OCT             1118  ...  2010  0         2.564220
1    Far South   NOV             1600  ...  2010  0         1.820250
2    Far South   DEC             1379  ...  2010  0         1.685819
3    Far South   JAN             1184  ...  2010  0         1.966777
10   Far South   AUG             2492  ...  2010  0         2.870968
..         ...   ...              ...  ...   ... ..              ...
408  St. Johns   OCT             1344  ...  2018  0         2.823529
409  St. Johns   NOV             1109  ...  2018  0         2.895561
412  St. Johns   FEB             1003  ...  2018  0         3.012012
418  St. Johns   AUG             2996  ...  2018  0         3.047813
419  St. Johns   SEP             1534  ...  2018  0         3.408889

[67 rows x 8 columns]

## Manipulating DataFrames: Sorting, Pivots, Crosstabs

In [ ]:
#read in shots df again
shots_df = pd.read_json('https://tf-assets-prod.s3.amazonaws.com/tf-curric/data-analytics-bootcamp/shots.json')

In [ ]:
#sort by year then month then visits(per month), could be year/month only
shots_df_sorted = shots_df.sort_values(by = ['year', 'month', 'visits'])
shots_df_sorted.head(3)

location month  number_of_shots    program_name  visits  year
42  St. Johns   APR              460       Big Shots     192  2010
18  Far South   APR              365       Big Shots     206  2010
6   Far South   APR              749  Shots for Tots     275  2010

In [ ]:
#create a month-year column
shots_df = shots_df.assign(month_year = shots_df.month + '/' + shots_df.year.astype(str))
shots_df.head()

location month  number_of_shots    program_name  visits  year month_year
0  Far South   OCT             1118  Shots for Tots     436  2010   OCT/2010
1  Far South   NOV             1600  Shots for Tots     879  2010   NOV/2010
2  Far South   DEC             1379  Shots for Tots     818  2010   DEC/2010
3  Far South   JAN             1184  Shots for Tots     602  2010   JAN/2010
4  Far South   FEB              761  Shots for Tots     337  2010   FEB/2010

In [ ]:
# Drop any duplicates that would mess up our pivot table
shots_df_clean = shots_df.drop_duplicates(['month_year','location'])
shots_df_clean
# Create a pivot table
shots_df_clean.pivot(index='month_year', columns='location', values='number_of_shots')
# search for pandas.DataFrame.pivot in the Pandas documentation
shots_df_clean

location month  number_of_shots    program_name  visits  year month_year
0    Far South   OCT             1118  Shots for Tots     436  2010   OCT/2010
1    Far South   NOV             1600  Shots for Tots     879  2010   NOV/2010
2    Far South   DEC             1379  Shots for Tots     818  2010   DEC/2010
3    Far South   JAN             1184  Shots for Tots     602  2010   JAN/2010
4    Far South   FEB              761  Shots for Tots     337  2010   FEB/2010
..         ...   ...              ...             ...     ...   ...        ...
415  St. Johns   MAY              719  Shots for Tots     287  2018   MAY/2018
416  St. Johns   JUN              541  Shots for Tots     207  2018   JUN/2018
417  St. Johns   JUL              727  Shots for Tots     282  2018   JUL/2018
418  St. Johns   AUG             2996  Shots for Tots     983  2018   AUG/2018
419  St. Johns   SEP             1534  Shots for Tots     450  2018   SEP/2018

[216 rows x 7 columns]

In [ ]:
# Search by program name to see total entries
pd.crosstab(shots_df['program_name'],shots_df['location'])
# search for crosstab in the Pandas documentation or hover

### Python test is autograded so you have unlimted attempts 🐼